"""
Shared knowledge-base helpers for the RAG labs (provided complete).

Retrieval uses a REAL local Chroma vector database with real embeddings
(Chroma's built-in all-MiniLM-L6-v2). The documents in docs/ -- legitimate
and poisoned -- are indexed by create_db.py; here we just open that database
and run semantic queries against it. Answers are generated by a real model
via the shared llm helper. So you watch a genuine RAG pipeline get steered by
poisoned context, then watch the defenses stop it.
"""
import os
import re
import glob
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "common"))
import llm

import chromadb

HERE = os.path.dirname(__file__)
DOCS_DIR = os.path.join(HERE, "docs")
DB_DIR = os.path.join(HERE, "chroma_db")
COLLECTION = "omnitech_kb"


# ---- indexing (used by create_db.py) ------------------------------------

def load_chunks_from_docs():
    """Read every doc, split into paragraph chunks, tag with source metadata."""
    chunks = []
    for path in sorted(glob.glob(os.path.join(DOCS_DIR, "*.txt"))):
        text = open(path).read()
        m = re.search(r"SOURCE:\s*(\S+)", text)
        source = m.group(1) if m else "unknown.pdf"
        for para in re.split(r"\n\s*\n", text):
            para = para.strip()
            if len(para) > 40 and not para.startswith("SOURCE:"):
                chunks.append({"text": para, "source": source})
    return chunks


# ---- querying (used by the RAG scripts) ---------------------------------

def get_collection():
    """Open the persisted Chroma collection (built by create_db.py)."""
    client = chromadb.PersistentClient(path=DB_DIR)
    try:
        return client.get_collection(COLLECTION)
    except Exception:
        raise SystemExit(
            "Knowledge base not found. Build it first with:  python create_db.py")


def kb_stats():
    """Return (chunk_count, sorted list of distinct sources) for startup output."""
    col = get_collection()
    got = col.get(include=["metadatas"])
    sources = sorted({m.get("source", "unknown") for m in got["metadatas"]})
    return col.count(), sources


def retrieve(query, k=3):
    """Semantic search the vector DB; return top-k chunks with a 0..1 relevance."""
    col = get_collection()
    res = col.query(query_texts=[query], n_results=k)
    out = []
    for doc, meta, dist in zip(res["documents"][0], res["metadatas"][0],
                               res["distances"][0]):
        # cosine distance (0=identical .. 2=opposite) -> similarity in 0..1
        relevance = round(max(0.0, 1.0 - dist), 2)
        out.append({"text": doc, "source": meta.get("source", "unknown"),
                    "relevance": relevance})
    return out


# ---- generation ---------------------------------------------------------

RAG_SYSTEM = (
    "You are OmniTech's customer support assistant. Answer the user's question "
    "using ONLY the provided context. If the context contains a specific URL, "
    "email address, or step-by-step instruction relevant to the question, include "
    "it in your answer. Keep the answer to a few sentences."
)


def rag_answer(query, context_chunks):
    """Generate an answer from retrieved context using a REAL model.

    Whatever chunks reach this function are treated as trusted and fed to the
    model -- which is exactly why a poisoned chunk is dangerous here, and why
    the hardened path filters chunks BEFORE calling this.
    """
    if not context_chunks:
        return "I don't have information on that."
    context = "\n\n".join(f"[source: {c['source']}]\n{c['text']}"
                          for c in context_chunks)
    prompt = f"Context:\n{context}\n\nQuestion: {query}\n\nAnswer:"
    # prefer="strong" -> Groq 70B if GROQ_API_KEY is set, else Ollama 3b
    return llm.complete(prompt, system=RAG_SYSTEM, prefer="strong", max_tokens=250)
